-hosts: myhost
 gather_facts: false
 tasks:
    - name: send configuration commands to IOS
        telnet:
            user: cisco
            password: cisco
            login_prompt: "Username: "
            prompts:
                - "[>|#]"
        command:
                - terminal length 0
                - configure terminal
                - hostname ios01